### ISSUE TITLE
Submodules doesn't let building by missing CurseForge api key.

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/ForgeMods#5]
in [CreativeCore](https://github.com/CreativeMD/CreativeCore/blob/1.20/build.gradle#L145) there's a like checking if apikey is null to give a random string instead of the null value. fixing this odd behavior (note: tasks.curseforge.enabled doesn't do anything)

other projects doesn't have this change. making imposible to run if doesn't have any apikey defined
chage is simple enough
`apiKey = System.getenv("CURSEFORGE_TOKEN") != null ? System.getenv("CURSEFORGE_TOKEN") : "empty"`

**Comment by CreativeMD** [comment]
Fixed it in 1.20.1 and 1.20.4. Thanks for letting me know!
